/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailSentRouteImport } from './routes/verify-email-sent'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutSettingsRouteImport } from './routes/_sidebar-layout.settings'
import { Route as SidebarLayoutConnectionsRouteImport } from './routes/_sidebar-layout.connections'
import { Route as SidebarLayoutChatLayoutRouteImport } from './routes/_sidebar-layout._chat-layout'
import { Route as SidebarLayoutStoriesIndexRouteImport } from './routes/_sidebar-layout.stories.index'
import { Route as SidebarLayoutSettingsIndexRouteImport } from './routes/_sidebar-layout.settings.index'
import { Route as SidebarLayoutChatLayoutIndexRouteImport } from './routes/_sidebar-layout._chat-layout.index'
import { Route as SidebarLayoutSharedChatShareIdRouteImport } from './routes/_sidebar-layout.shared-chat.$shareId'
import { Route as SidebarLayoutSettingsUsageRouteImport } from './routes/_sidebar-layout.settings.usage'
import { Route as SidebarLayoutSettingsMemoryRouteImport } from './routes/_sidebar-layout.settings.memory'
import { Route as SidebarLayoutSettingsAccountRouteImport } from './routes/_sidebar-layout.settings.account'
import { Route as SidebarLayoutSchemaSlugRouteImport } from './routes/_sidebar-layout.schema.$slug'
import { Route as SidebarLayoutChatLayoutChatIdRouteImport } from './routes/_sidebar-layout._chat-layout.$chatId'
import { Route as SidebarLayoutStoriesSharedShareIdRouteImport } from './routes/_sidebar-layout.stories.shared.$shareId'
import { Route as SidebarLayoutStoriesPreviewChatIdStorySlugRouteImport } from './routes/_sidebar-layout.stories.preview.$chatId.$storySlug'

const VerifyEmailSentRoute = VerifyEmailSentRouteImport.update({
  id: '/verify-email-sent',
  path: '/verify-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutSettingsRoute = SidebarLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutConnectionsRoute =
  SidebarLayoutConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutChatLayoutRoute = SidebarLayoutChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutStoriesIndexRoute =
  SidebarLayoutStoriesIndexRouteImport.update({
    id: '/stories/',
    path: '/stories/',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsIndexRoute =
  SidebarLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutChatLayoutIndexRoute =
  SidebarLayoutChatLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutSharedChatShareIdRoute =
  SidebarLayoutSharedChatShareIdRouteImport.update({
    id: '/shared-chat/$shareId',
    path: '/shared-chat/$shareId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsUsageRoute =
  SidebarLayoutSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsMemoryRoute =
  SidebarLayoutSettingsMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsAccountRoute =
  SidebarLayoutSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSchemaSlugRoute = SidebarLayoutSchemaSlugRouteImport.update({
  id: '/schema/$slug',
  path: '/schema/$slug',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutChatLayoutChatIdRoute =
  SidebarLayoutChatLayoutChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutStoriesSharedShareIdRoute =
  SidebarLayoutStoriesSharedShareIdRouteImport.update({
    id: '/stories/shared/$shareId',
    path: '/stories/shared/$shareId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutStoriesPreviewChatIdStorySlugRoute =
  SidebarLayoutStoriesPreviewChatIdStorySlugRouteImport.update({
    id: '/stories/preview/$chatId/$storySlug',
    path: '/stories/preview/$chatId/$storySlug',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/connections': typeof SidebarLayoutConnectionsRoute
  '/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/schema/$slug': typeof SidebarLayoutSchemaSlugRoute
  '/settings/account': typeof SidebarLayoutSettingsAccountRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/shared-chat/$shareId': typeof SidebarLayoutSharedChatShareIdRoute
  '/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/stories/': typeof SidebarLayoutStoriesIndexRoute
  '/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/stories/preview/$chatId/$storySlug': typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/connections': typeof SidebarLayoutConnectionsRoute
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/schema/$slug': typeof SidebarLayoutSchemaSlugRoute
  '/settings/account': typeof SidebarLayoutSettingsAccountRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/shared-chat/$shareId': typeof SidebarLayoutSharedChatShareIdRoute
  '/settings': typeof SidebarLayoutSettingsIndexRoute
  '/stories': typeof SidebarLayoutStoriesIndexRoute
  '/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/stories/preview/$chatId/$storySlug': typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/_sidebar-layout/_chat-layout': typeof SidebarLayoutChatLayoutRouteWithChildren
  '/_sidebar-layout/connections': typeof SidebarLayoutConnectionsRoute
  '/_sidebar-layout/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/_sidebar-layout/_chat-layout/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/_sidebar-layout/schema/$slug': typeof SidebarLayoutSchemaSlugRoute
  '/_sidebar-layout/settings/account': typeof SidebarLayoutSettingsAccountRoute
  '/_sidebar-layout/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/_sidebar-layout/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/_sidebar-layout/shared-chat/$shareId': typeof SidebarLayoutSharedChatShareIdRoute
  '/_sidebar-layout/_chat-layout/': typeof SidebarLayoutChatLayoutIndexRoute
  '/_sidebar-layout/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/_sidebar-layout/stories/': typeof SidebarLayoutStoriesIndexRoute
  '/_sidebar-layout/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/_sidebar-layout/stories/preview/$chatId/$storySlug': typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/verify-email-sent'
    | '/connections'
    | '/settings'
    | '/$chatId'
    | '/schema/$slug'
    | '/settings/account'
    | '/settings/memory'
    | '/settings/usage'
    | '/shared-chat/$shareId'
    | '/settings/'
    | '/stories/'
    | '/stories/shared/$shareId'
    | '/stories/preview/$chatId/$storySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/verify-email-sent'
    | '/connections'
    | '/$chatId'
    | '/schema/$slug'
    | '/settings/account'
    | '/settings/memory'
    | '/settings/usage'
    | '/shared-chat/$shareId'
    | '/settings'
    | '/stories'
    | '/stories/shared/$shareId'
    | '/stories/preview/$chatId/$storySlug'
  id:
    | '__root__'
    | '/_sidebar-layout'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/verify-email-sent'
    | '/_sidebar-layout/_chat-layout'
    | '/_sidebar-layout/connections'
    | '/_sidebar-layout/settings'
    | '/_sidebar-layout/_chat-layout/$chatId'
    | '/_sidebar-layout/schema/$slug'
    | '/_sidebar-layout/settings/account'
    | '/_sidebar-layout/settings/memory'
    | '/_sidebar-layout/settings/usage'
    | '/_sidebar-layout/shared-chat/$shareId'
    | '/_sidebar-layout/_chat-layout/'
    | '/_sidebar-layout/settings/'
    | '/_sidebar-layout/stories/'
    | '/_sidebar-layout/stories/shared/$shareId'
    | '/_sidebar-layout/stories/preview/$chatId/$storySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyEmailSentRoute: typeof VerifyEmailSentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email-sent': {
      id: '/verify-email-sent'
      path: '/verify-email-sent'
      fullPath: '/verify-email-sent'
      preLoaderRoute: typeof VerifyEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/settings': {
      id: '/_sidebar-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarLayoutSettingsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/connections': {
      id: '/_sidebar-layout/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof SidebarLayoutConnectionsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout': {
      id: '/_sidebar-layout/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/stories/': {
      id: '/_sidebar-layout/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof SidebarLayoutStoriesIndexRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/': {
      id: '/_sidebar-layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SidebarLayoutSettingsIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/_chat-layout/': {
      id: '/_sidebar-layout/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/shared-chat/$shareId': {
      id: '/_sidebar-layout/shared-chat/$shareId'
      path: '/shared-chat/$shareId'
      fullPath: '/shared-chat/$shareId'
      preLoaderRoute: typeof SidebarLayoutSharedChatShareIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/usage': {
      id: '/_sidebar-layout/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SidebarLayoutSettingsUsageRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/memory': {
      id: '/_sidebar-layout/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SidebarLayoutSettingsMemoryRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/account': {
      id: '/_sidebar-layout/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SidebarLayoutSettingsAccountRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/schema/$slug': {
      id: '/_sidebar-layout/schema/$slug'
      path: '/schema/$slug'
      fullPath: '/schema/$slug'
      preLoaderRoute: typeof SidebarLayoutSchemaSlugRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout/$chatId': {
      id: '/_sidebar-layout/_chat-layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof SidebarLayoutChatLayoutChatIdRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/stories/shared/$shareId': {
      id: '/_sidebar-layout/stories/shared/$shareId'
      path: '/stories/shared/$shareId'
      fullPath: '/stories/shared/$shareId'
      preLoaderRoute: typeof SidebarLayoutStoriesSharedShareIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/stories/preview/$chatId/$storySlug': {
      id: '/_sidebar-layout/stories/preview/$chatId/$storySlug'
      path: '/stories/preview/$chatId/$storySlug'
      fullPath: '/stories/preview/$chatId/$storySlug'
      preLoaderRoute: typeof SidebarLayoutStoriesPreviewChatIdStorySlugRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
  }
}

interface SidebarLayoutChatLayoutRouteChildren {
  SidebarLayoutChatLayoutChatIdRoute: typeof SidebarLayoutChatLayoutChatIdRoute
  SidebarLayoutChatLayoutIndexRoute: typeof SidebarLayoutChatLayoutIndexRoute
}

const SidebarLayoutChatLayoutRouteChildren: SidebarLayoutChatLayoutRouteChildren =
  {
    SidebarLayoutChatLayoutChatIdRoute: SidebarLayoutChatLayoutChatIdRoute,
    SidebarLayoutChatLayoutIndexRoute: SidebarLayoutChatLayoutIndexRoute,
  }

const SidebarLayoutChatLayoutRouteWithChildren =
  SidebarLayoutChatLayoutRoute._addFileChildren(
    SidebarLayoutChatLayoutRouteChildren,
  )

interface SidebarLayoutSettingsRouteChildren {
  SidebarLayoutSettingsAccountRoute: typeof SidebarLayoutSettingsAccountRoute
  SidebarLayoutSettingsMemoryRoute: typeof SidebarLayoutSettingsMemoryRoute
  SidebarLayoutSettingsUsageRoute: typeof SidebarLayoutSettingsUsageRoute
  SidebarLayoutSettingsIndexRoute: typeof SidebarLayoutSettingsIndexRoute
}

const SidebarLayoutSettingsRouteChildren: SidebarLayoutSettingsRouteChildren = {
  SidebarLayoutSettingsAccountRoute: SidebarLayoutSettingsAccountRoute,
  SidebarLayoutSettingsMemoryRoute: SidebarLayoutSettingsMemoryRoute,
  SidebarLayoutSettingsUsageRoute: SidebarLayoutSettingsUsageRoute,
  SidebarLayoutSettingsIndexRoute: SidebarLayoutSettingsIndexRoute,
}

const SidebarLayoutSettingsRouteWithChildren =
  SidebarLayoutSettingsRoute._addFileChildren(
    SidebarLayoutSettingsRouteChildren,
  )

interface SidebarLayoutRouteChildren {
  SidebarLayoutChatLayoutRoute: typeof SidebarLayoutChatLayoutRouteWithChildren
  SidebarLayoutConnectionsRoute: typeof SidebarLayoutConnectionsRoute
  SidebarLayoutSettingsRoute: typeof SidebarLayoutSettingsRouteWithChildren
  SidebarLayoutSchemaSlugRoute: typeof SidebarLayoutSchemaSlugRoute
  SidebarLayoutSharedChatShareIdRoute: typeof SidebarLayoutSharedChatShareIdRoute
  SidebarLayoutStoriesIndexRoute: typeof SidebarLayoutStoriesIndexRoute
  SidebarLayoutStoriesSharedShareIdRoute: typeof SidebarLayoutStoriesSharedShareIdRoute
  SidebarLayoutStoriesPreviewChatIdStorySlugRoute: typeof SidebarLayoutStoriesPreviewChatIdStorySlugRoute
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutChatLayoutRoute: SidebarLayoutChatLayoutRouteWithChildren,
  SidebarLayoutConnectionsRoute: SidebarLayoutConnectionsRoute,
  SidebarLayoutSettingsRoute: SidebarLayoutSettingsRouteWithChildren,
  SidebarLayoutSchemaSlugRoute: SidebarLayoutSchemaSlugRoute,
  SidebarLayoutSharedChatShareIdRoute: SidebarLayoutSharedChatShareIdRoute,
  SidebarLayoutStoriesIndexRoute: SidebarLayoutStoriesIndexRoute,
  SidebarLayoutStoriesSharedShareIdRoute:
    SidebarLayoutStoriesSharedShareIdRoute,
  SidebarLayoutStoriesPreviewChatIdStorySlugRoute:
    SidebarLayoutStoriesPreviewChatIdStorySlugRoute,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyEmailSentRoute: VerifyEmailSentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
